Repository LAB-MI/candilibV2, pull requests merged in 2019-10, with the labels that each got.

#749 Tech/add e2e tests with cypress
  .gitignore
  .travis.yml
  Makefile
  Makefile.mk
  README.md
  ci/init-db-e2e.sh
  ci/run-tests.sh
  client/.gitignore
  client/README.md
  client/cypress.env.json
  client/cypress.json
  client/docker-compose.e2e.yml
  client/docker-compose.prod.front.yml
  client/e2e-entrypoint.sh
  client/e2e.Dockerfile
  client/package-lock.json
  client/package.json
  client/src/views/admin/components/AdminHeader.vue
  client/src/views/admin/components/SearchCandidat.vue
  client/src/views/admin/components/SearchInspecteur.vue
  client/src/views/admin/components/Whitelist.vue
  client/src/views/admin/components/schedule/ScheduleInspector.vue
  client/src/views/admin/components/schedule/ScheduleInspectorButton.vue
  client/src/views/admin/components/schedule/ScheduleManager.vue
  client/src/views/candidat/components/AlreadySignedUp.vue
  client/src/views/candidat/components/CandidatHeader.vue
  client/src/views/candidat/components/LandingPage.vue
  client/tests/e2e/plugins/index.js
  client/tests/e2e/specs/adminDashboard.js
  client/tests/e2e/specs/adminLogin.js
  client/tests/e2e/specs/adminPlaces.js
  client/tests/e2e/specs/adminPlanning.js
  client/tests/e2e/specs/adminWhitelist.js
  client/tests/e2e/specs/aurigeRefusals.js
  client/tests/e2e/specs/candidateFront.js
  client/tests/e2e/specs/candidateLogin.js
  client/tests/e2e/specs/delayAfterFailure.js
  client/tests/e2e/specs/interactions.js
  client/tests/e2e/specs/test.js
  client/tests/e2e/support/commands.js
  client/tests/e2e/support/index.js
  server/Makefile
  server/README.md
  server/docker-compose.dev.yml
Labels: devops, tech

#750 Fix/Factorisation des tests Cypress et utilisation en environnement dev
  README.md
  client/tests/e2e/specs/adminDashboard.js
  client/tests/e2e/specs/adminLogin.js
  client/tests/e2e/specs/adminPlaces.js
  client/tests/e2e/specs/adminPlanning.js
  client/tests/e2e/specs/adminWhitelist.js
  client/tests/e2e/specs/aurigeRefusals.js
  client/tests/e2e/specs/candidateFront.js
  client/tests/e2e/specs/candidateLogin.js
  client/tests/e2e/specs/delayAfterFailure.js
  client/tests/e2e/specs/interactions.js
  client/tests/e2e/support/commands.js
  client/tests/e2e/support/mailHogCommands.js
  server/Makefile
  server/docker-compose.dev.yml
Labels: tech

#746 Qualif/v2.4 rc2
  client/src/candidat.js
  client/src/main.styl
  client/src/store/auth.js
  client/src/store/time-slots.js
  client/src/store/utils/index.js
  client/src/views/admin/components/CandidatsList.vue
  client/src/views/admin/components/ImportPlacesValidation.vue
  client/src/views/admin/components/Monitors.vue
  client/src/views/admin/components/ProfileInfo.vue
  client/src/views/admin/components/SearchCandidat.vue
  client/src/views/admin/components/Whitelist.vue
  client/src/views/admin/components/schedule/ScheduleInspectorDetails.vue
  client/src/views/candidat/Candidat.vue
  client/src/views/candidat/components/AlreadySignedUp.vue
  client/src/views/candidat/components/CandidatHeader.vue
  client/src/views/candidat/components/SignupForm.vue
  client/src/views/candidat/components/center-selection/CenterSelectionContent.vue
  client/src/views/candidat/components/mentions-legales/MentionsLegalesJson.js
  client/src/views/candidat/components/time-slots-selection/TimeSlot.vue
  client/tests/e2e/specs/aurigeRefusals.js
  client/tests/e2e/specs/candidateFront.js
  client/tests/e2e/specs/candidateLogin.js
  client/tests/e2e/specs/delayAfterFailure.js
  client/tests/e2e/support/commands.js
  server/src/models/__tests__/candidats.js
  server/src/models/__tests__/index.js
  server/src/models/__tests__/reservations.js
  server/src/models/__tests__/users.js
  server/src/models/candidat/candidat.queries.js
  server/src/models/candidat/candidat.queries.spec.js
  server/src/models/place/place.model.js
  server/src/models/place/place.queries.js
  server/src/models/place/place.queries.spec.js
  server/src/models/user/user.model.js
  server/src/routes/admin/business/__tests__/candidats-aurige.js
  server/src/routes/admin/business/synchro-aurige.js
  server/src/routes/admin/business/synchro-aurige.spec.js
  server/src/routes/admin/candidats.controllers.js
  server/src/routes/admin/candidats.controllers.spec.js
  server/src/routes/admin/places.business.js
  server/src/routes/admin/places.controllers.js
  server/src/routes/admin/places.controllers.spec.js
  server/src/routes/admin/reservations.controllers.js
  server/src/routes/admin/reservations.controllers.spec.js
  server/src/routes/business/mail/cancel-booking-by-admin-template.js
  server/src/routes/business/mail/cancel-booking-template.js
  server/src/routes/business/mail/convocation-template.js
  server/src/routes/business/message-templates.js
  server/src/routes/business/send-mail.js
  server/src/routes/candidat/places.business.js
  server/src/routes/candidat/places.controllers.js
  server/src/routes/candidat/reservations.controllers.js
  server/src/routes/candidat/reservations.controllers.spec.js
  server/src/routes/common/centre.controllers.spec.js
  server/src/routes/common/reason.constants.js
  server/src/util/constants.js
Labels: Release

#759 Fix storybook
  client/package-lock.json
  client/package.json
  client/src/views/admin/components/FillSchedulesPlaces.stories.js
  client/src/views/admin/components/FillSchedulesPlaces.vue
  server/src/routes/business/mail/cancel-booking-template.js
  server/src/routes/business/mail/convocation-template.js
  server/src/routes/candidat/places.business.js
Labels: bug, tech

#751 Feat/add archive places by admin
  server/src/models/archived-place/__tests__/expect-archive-place.js
  server/src/models/archived-place/archived-place.model.js
  server/src/models/archived-place/archived-place.queries.js
  server/src/models/archived-place/archived-place.queries.spec.js
  server/src/models/archived-place/index.js
  server/src/models/place/place.model.js
  server/src/models/place/place.queries.js
  server/src/models/place/place.queries.spec.js
  server/src/routes/admin/places.controllers.spec.js
  server/src/util/__mocks__/token.js
Labels: server, tech

#709 :lipstick: Set first A of Candilib in red
  client/src/candidat.js
  client/src/views/Message.vue
Labels: bug, candidat

#724 Add tooltips with information of colors label
  client/src/admin.js
  client/src/views/admin/components/DataTableWeekMonitor.vue
Labels: admin, enhancement

#762 :bug: remove result find the whitelisteds in log
  server/src/routes/admin/whitelisted.controllers.js
Labels: tech

#716 ETD display only fetched weeks
  client/src/store/admin.js
  client/src/views/admin/components/DataTableWeekMonitor.vue
  client/src/views/admin/components/WeekMonitor.vue
  client/src/views/admin/components/schedule/ScheduleInspector.vue
Labels: admin

#778 :arrow_up: Upgrade npm dependencies on server
  server/package-lock.json
  server/package.json
  server/src/mongo-connection.js
Labels: bug, tech

#785 New Release ready
  client/README.md
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/admin.js
  client/src/candidat.js
  client/src/store/admin.js
  client/src/views/Message.vue
  client/src/views/admin/components/DataTableWeekMonitor.vue
  client/src/views/admin/components/WeekMonitor.vue
  client/src/views/admin/components/schedule/ScheduleInspector.vue
  server/src/models/centre/centre.queries.js
  server/src/models/place/place.model.js
  server/src/models/place/place.queries.js
  server/src/routes/admin/business/synchro-aurige.js
  server/src/routes/admin/places.business.js
  server/src/routes/admin/whitelisted.controllers.js
  server/src/routes/business/build-mail-cancellation-by-admin.js
  server/src/routes/business/build-mail-cancellation.js
  server/src/routes/business/build-mail-convocation.js
  server/src/routes/business/build-mail-failure-exam.js
  server/src/routes/business/send-mail-schedule-inspecteur.js
  server/src/routes/candidat/places.business.js
  server/src/util/date-util.js
  server/src/util/date-util.spec.js
  server/src/util/date.util.js
  server/src/util/index.js
Labels: Release

#725 Feat/create route api change password
  ci/run-tests.sh
  client/cypress.env.json
  client/package-lock.json
  client/package.json
  client/src/api/api-paths.js
  client/src/api/index.js
  client/src/router.js
  client/src/store/admin.js
  client/src/views/admin/components/EmailPasswordReset.stories.js
  client/src/views/admin/components/EmailPasswordReset.vue
  client/src/views/admin/components/Login.vue
  client/src/views/admin/components/ResetPassword.vue
  client/tests/e2e/specs/adminLogin.js
  client/tests/e2e/specs/adminPlanning.js
  client/tests/e2e/specs/adminResetPassword.js
  client/tests/e2e/support/commands.js
  server/Makefile
  server/docker-compose.dev.yml
  server/docker-compose.prod.all.yml
  server/docker-compose.prod.api.yml
  server/package-lock.json
  server/src/app.js
  server/src/config.js
  server/src/index.js
  server/src/models/place/place.queries.js
  server/src/models/user/user.model.js
  server/src/models/user/user.queries.js
  server/src/routes/admin/admin.controllers.spec.js
  server/src/routes/admin/business/synchro-aurige.js
  server/src/routes/admin/index.js
  server/src/routes/auth/admin.controllers.js
  server/src/routes/auth/admin.controllers.spec.js
  server/src/routes/auth/admin.spec.js
  server/src/routes/auth/index.js
  server/src/routes/business/send-mail-confirmation-new-password.js
  server/src/routes/business/send-mail-reset-password.js
  server/src/routes/candidat/places.business.js
  server/src/routes/index.js
Labels: admin, enhancement

#677 Improve newcomer docs
  README.md
  server/.env-example
  server/README.md
Labels: docs, enhancement

#765 Fix/log too long and no homogenous
  server/src/routes/admin/places.controllers.js
  server/src/routes/candidat/places.business.js
  server/src/routes/candidat/reservations.controllers.js
Labels: bug, tech

#798 Feat/create route api change paswword
  ci/run-tests.sh
  client/cypress.env.json
  client/package-lock.json
  client/package.json
  client/src/api/api-paths.js
  client/src/api/index.js
  client/src/router.js
  client/src/store/admin.js
  client/src/util/transformers.js
  client/src/views/admin/components/EmailPasswordReset.stories.js
  client/src/views/admin/components/EmailPasswordReset.vue
  client/src/views/admin/components/Login.vue
  client/src/views/admin/components/ResetPassword.vue
  client/tests/e2e/specs/adminLogin.js
  client/tests/e2e/specs/adminPlanning.js
  client/tests/e2e/specs/adminResetPassword.js
  client/tests/e2e/support/commands.js
  server/Makefile
  server/docker-compose.dev.yml
  server/docker-compose.prod.all.yml
  server/docker-compose.prod.api.yml
  server/jsdoc-config.js
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/config.js
  server/src/index.js
  server/src/models/place/place.queries.js
  server/src/models/user/user.model.js
  server/src/models/user/user.queries.js
  server/src/routes/admin/admin.controllers.spec.js
  server/src/routes/admin/business/synchro-aurige.js
  server/src/routes/admin/index.js
  server/src/routes/auth/admin-controllers.js
  server/src/routes/auth/admin.controllers.spec.js
  server/src/routes/auth/admin.spec.js
  server/src/routes/auth/index.js
  server/src/routes/business/send-mail-confirmation-new-password.js
  server/src/routes/business/send-mail-reset-password.js
  server/src/routes/candidat/places.business.js
  server/src/routes/index.js
Labels: admin, enhancement

#766 Doc/documentation open api admin Partie 1
  client/package.json
  docs/CandilibV2.postman_collection.json
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/routes/admin/admin.controllers.js
  server/src/routes/admin/candidats.controllers.js
  server/src/routes/admin/candidats.controllers.spec.js
  server/src/routes/admin/index.js
  server/src/routes/admin/inspecteurs.controllers.js
  server/src/routes/admin/message.constants.js
  server/src/routes/admin/middlewares/verify-access-aurige.js
  server/src/routes/admin/middlewares/verify-repartiteur-departement.js
  server/src/routes/admin/whitelisted.controllers.js
Labels: admin, docs
