Repository LAB-MI/candilibV2, pull requests merged in 2019-02, with the labels that each got.

#34 Feat/front office implement presignup
  README.md
  client/.stylelintignore
  client/.stylelintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/api/api-paths.js
  client/src/api/index.js
  client/src/assets/bg-presignup.jpg
  client/src/assets/images/lab_100.png
  client/src/assets/images/logo_mi_40x50.png
  client/src/assets/images/securite_routiere_70x27.png
  client/src/components/form-inputs/input-file.vue
  client/src/main.css
  client/src/plugins/vuetify.js
  client/src/router-checks.js
  client/src/router.js
  client/src/store/auth.js
  client/src/store/candidat.js
  client/src/store/candidats.js
  client/src/store/index.js
  client/src/store/whitelist.js
  client/src/util/calendar.spec.js
  client/src/views/AdminHome.vue
  client/src/views/CandidatHome.vue
  client/src/views/admin/Admin.vue
  client/src/views/admin/components/Aurige.vue
  client/src/views/admin/components/CandidatsList.vue
  client/src/views/admin/components/Login.vue
  client/src/views/admin/components/Login.vue.spec.js
  client/src/views/admin/components/Whitelist.vue
  client/src/views/candidat/Candidat.vue
  client/src/views/candidat/components/Login.vue
  client/src/views/candidat/components/LoginForm.vue
  client/src/views/candidat/components/Signup.vue
  client/src/views/candidat/components/SignupForm.vue
  client/src/views/candidat/components/index.js
  client/vue.config.js
  docs/CandilibV2.postman_collection.json
  server/config/polyfills.js
  server/package-lock.json
  server/package.json
  server/src/config.js
  server/src/models/candidat/candidat.model.js
  server/src/models/candidat/candidat.queries.js
  server/src/models/candidat/candidat.queries.spec.js
  server/src/routes/auth/candidat.controllers.js
  server/src/routes/auth/index.js
  server/src/routes/business/send-mail.js
  server/src/routes/candidat/__mocks__/candidat.business.js
  server/src/routes/candidat/candidat.business.js
  server/src/routes/candidat/candidat.controllers.js
  server/src/routes/candidat/candidat.controllers.spec.js
  server/src/routes/candidat/index.js
  server/src/routes/index.js
  server/src/util/index.js
Labels: enhancement

#36 Implement 'Mes informations' component
  client/src/api/api-paths.js
  client/src/api/index.js
  client/src/components/HeaderIcon.vue
  client/src/components/IconWithTooltip.vue
  client/src/components/index.js
  client/src/main.css
  client/src/router.js
  client/src/store/candidat.js
  client/src/views/admin/components/AdminHeader.vue
  client/src/views/admin/components/Whitelist.vue
  client/src/views/candidat/Candidat.vue
  client/src/views/candidat/Faq.vue
  client/src/views/candidat/Legal.vue
  client/src/views/candidat/components/CandidatHeader.vue
  client/src/views/candidat/components/MyProfile.vue
  client/src/views/candidat/components/NavigationDrawer.vue
  client/src/views/candidat/components/ProfileInfo.vue
  client/src/views/candidat/components/SignupForm.vue
  server/package-lock.json
  server/src/models/candidat/candidat.queries.js
  server/src/routes/candidat/candidat.controllers.js
  server/src/routes/candidat/index.js
  server/src/routes/middlewares/verify-token.js
Labels: enhancement

#47 Display version
  client/src/components/AppVersion.vue
  client/src/views/admin/Admin.vue
  client/src/views/admin/components/AdminFooter.vue
  client/src/views/admin/components/Login.vue
  client/src/views/candidat/Candidat.vue
  client/src/views/candidat/components/CandidatFooter.vue
  client/src/views/candidat/components/SignupForm.vue
Labels: enhancement

#46 Fix export candidats
  server/src/models/candidat/__TESTS__/candidats.js
  server/src/models/candidat/candidat.queries.spec.js
  server/src/routes/admin/candidats.controller.spec.js
  server/src/routes/admin/candidats.controllers.js
  server/src/routes/admin/middlewares/__mocks__/verify-admin-level.js
  server/src/routes/middlewares/__mocks__/verify-token.js
Labels: bug

#52 update logger level
  server/src/routes/admin/business/synchro-aurige.js
Labels: enhancement

#51 secure mongoDB
  server/.env-example
  server/README.md
  server/db/init-mongo.sh
  server/dev-setup/mongo-init.js
  server/docker-compose.dev.db.yml
  server/docker-compose.dev.yml
  server/src/config.js
  server/src/mongo-connection.js
Labels: enhancement

#49 Feat/ask email validation to candidat
  client/src/api/index.js
  client/src/components/AppVersion.vue
  client/src/constants.js
  client/src/main.css
  client/src/router-checks.js
  client/src/router.js
  client/src/store/candidat.js
  client/src/views/Message.vue
  client/src/views/admin/components/AurigeValidation.vue
  client/src/views/candidat/Candidat.vue
  client/src/views/candidat/components/EmailValidationComponent.vue
  client/src/views/candidat/components/Signup.vue
  client/src/views/candidat/components/SignupForm.vue
  client/src/views/candidat/components/index.js
  server/dev-setup/candidats.json
  server/package-lock.json
  server/package.json
  server/src/models/candidat/candidat.model.js
  server/src/models/candidat/candidat.queries.js
  server/src/routes/admin/business/synchro-aurige.js
  server/src/routes/auth/candidat.controllers.js
  server/src/routes/business/message-templates.js
  server/src/routes/candidat/candidat.business.js
  server/src/routes/candidat/candidat.controllers.js
  server/src/routes/candidat/candidat.controllers.spec.js
  server/src/routes/candidat/index.js
  server/src/routes/index.js
  server/src/util/constants.js
Labels: enhancement

#57 Fix inconsistencies in environment variables
  client/src/api/index.js
  server/dev-setup/index.js
  server/dev-setup/mongo-init.js
  server/dev-setup/setup.js
  server/src/mongo-connection.js
Labels: bug

#55 Differentiate admin and candidat token key
  client/src/App.vue
  client/src/api/index.js
  client/src/constants.js
  client/src/router-checks.js
  client/src/router.js
  client/src/store/auth.js
  client/src/views/CandidatHome.vue
  client/src/views/admin/Admin.vue
  client/src/views/admin/components/AdminHeader.vue
  client/src/views/admin/components/Login.vue
Labels: enhancement

#59 Use CANDIDAT_TOKEN_STORAGE_KEY instead of hard-coded 'token'
  client/src/router-checks.js
Labels: bug

#61 Set a readable color for error
  client/src/plugins/vuetify.js
Labels: enhancement

#63 Remove reference to Signup
  client/src/views/CandidatHome.vue
Labels: bug

#65 Handle correctly the env vars #64
  .travis.yml
  Makefile
  Makefile.mk
  client/.env.admin
  client/.env.candidat
  client/.env.development
  client/Dockerfile
  client/docker-compose.dev.yml
  client/docker-compose.prod.front.yml
  client/nginx/nginx-run-admin.template
  client/nginx/nginx-run-candidat.template
  client/nginx/nginx.template
  client/nginx/run.sh
  client/package.json
  client/src/router.js
  client/src/views/CandidatHome.vue
  server/docker-compose.dev.yml
  server/docker-compose.prod.all.yml
  server/docker-compose.prod.api.yml
  server/src/models/candidat/candidat.queries.spec.js
  server/src/models/whitelisted/whitelisted.queries.spec.js
  tests/test-up-candilib.sh
  tests/test-up-front-admin.sh
  tests/test-up-front-candidat.sh
Labels: enhancement

#58 Feat/archive candidat instead of deleting them #53
  server/package-lock.json
  server/package.json
  server/src/models/archived-candidat/archived-candidat.model.js
  server/src/models/archived-candidat/archived-candidat.queries.js
  server/src/models/archived-candidat/archived-candidat.queries.spec.js
  server/src/models/archived-candidat/index.js
  server/src/models/candidat/candidat.queries.js
  server/src/routes/admin/business/__tests__/aurige.json
  server/src/routes/admin/business/__tests__/candidats.json
  server/src/routes/admin/business/synchro-aurige.js
  server/src/routes/admin/business/synchro-aurige.spec.js
  server/src/routes/business/__mocks__/send-mail.js
  server/src/routes/business/message-templates.js
  server/src/util/constants.js
Labels: enhancement

#71 Fix/security npm audit before production
  client/Dockerfile
  client/package-lock.json
  server/Dockerfile
Labels: enhancement

#87 Feat/devops integrate ci build
  .travis.yml
  ci/run-tests.sh
Labels: devops

#88 documentation modèle de données
  docs/Architecture.md
  docs/Principes.md
  docs/archi_gene_candilib-Page-2.png
  docs/candilib_V1_data_model.png
  docs/candilib_V2_data_model.png
Labels: admin, enhancement

#102 Tech/add storybook #96
  client/config/storybook/addons.js
  client/config/storybook/config.js
  client/package-lock.json
  client/package.json
  client/src/components/AppSnackbar.vue
  client/src/components/PureAppSnackbar.vue
  client/src/stories/admin.stories.js
  client/src/stories/candidat.stories.js
  client/src/stories/common.stories.js
  client/src/views/admin/components/AdminCalendar.vue
  client/src/views/admin/components/AdminFooter.vue
  client/src/views/admin/components/AdminHeader.vue
  client/src/views/admin/components/Aurige.vue
  client/src/views/admin/components/CandidatsList.vue
  client/src/views/admin/components/Whitelist.vue
  client/src/views/candidat/components/CandidatFooter.vue
  client/src/views/candidat/components/CandidatHeader.vue
  client/src/views/candidat/components/EmailValidationComponent.vue
  client/src/views/candidat/components/MyProfile.vue
  client/src/views/candidat/components/NavigationDrawer.vue
  client/src/views/candidat/components/ProfileInfo.vue
  client/src/views/candidat/components/SignupForm.vue
Labels: tech

#95 return the results of import places
  server/src/routes/admin/places.controllers.js
Labels: admin, enhancement

#91 Feat/import places
  client/src/api/api-paths.js
  client/src/views/admin/components/AdminCalendar.vue
  client/src/views/admin/components/AdminImportPlaces.vue
  client/src/views/admin/components/Aurige.vue
  client/src/views/admin/components/ImportFile.vue
Labels: admin, enhancement

#104 Add link tags to storybook stories
  client/config/storybook/preview-head.html
Labels: enhancement, tech

#105 Feat/filter status synchro aurige
  client/src/stories/admin.stories.js
  client/src/views/admin/components/AgGridAurigeStatusFilter.vue
  client/src/views/admin/components/AurigeValidation.vue
Labels: admin, enhancement

#92 Feat/synchro empecher double synchro
  client/src/components/UploadFile.vue
  client/src/components/form-inputs/input-file.vue
  client/src/store/aurige.js
  client/src/store/candidats.js
  client/src/views/admin/components/AdminImportPlaces.vue
  client/src/views/admin/components/Aurige.vue
  server/dev-setup/candidats.json
  server/src/models/candidat/candidat.queries.js
Labels: admin, enhancement
