Repository LAB-MI/candilibV2, pull requests merged in 2020-06, with the labels that each got.

#1159 Fix/upper case name of center #1158
  client/cypress.env.json
  client/src/views/admin/components/centres/CenterForm.vue
  client/src/views/candidat/components/center-selection/arrayTestOfCenters.js
  client/tests/e2e/specs/admin-centres.js
  client/tests/e2e/specs/adminLogin.js
  client/tests/e2e/specs/adminPlanning.js
  server/dev-setup/centres.json
  server/src/models/__tests__/centres.js
  server/src/models/centre/centre-model.js
  server/src/models/centre/centre-queries.spec.js
  server/src/routes/admin/__tests__/candidats-stat.js
  server/src/routes/admin/business/__tests__/places-aurige.js
  server/src/routes/admin/places-business.spec.js
  server/src/routes/candidat/departement-controllers.spec.js
  server/src/routes/common/centre-business.spec.js
  server/src/routes/common/centre-controllers.spec.js
Labels: admin, bug, client, server

#1157 tech/improve performance
  client/src/assets/bg-login.jpg
  client/src/assets/images/beta.png
  client/src/assets/images/lab_100.png
  client/src/assets/images/logo_mi_40x50.png
  client/src/assets/images/logo_securite_routiere.png
  client/src/assets/images/securite_routiere_70x27.png
  client/src/router.js
Labels: tech

#1104 :tada: create app rest to manage mongodb
  Makefile
  client/cypress.env.json
  client/docker-compose.e2e.yml
  client/tests/e2e/specs/admin-centres.js
  client/tests/e2e/support/commands.js
  server/Makefile
  server/db/app/Dockerfile
  server/db/app/app.js
  server/db/app/index.js
  server/db/app/package-lock.json
  server/db/app/package.json
  server/docker-compose.dev.yml
Labels: tech

#1194 fix/error-wording-faq-#1141
  client/src/views/candidat/components/faq/FaqJson.js
Labels: bug, wording

#1202 Fix/unit test for display new palces after 12h
  server/package-lock.json
  server/package.json
  server/src/models/__tests__/places.js
  server/src/routes/candidat/places-business.spec.js
  server/src/routes/candidat/places-controllers.spec.js
  server/src/routes/candidat/util/date-to-display.js
  server/src/util/date-util.js
  server/src/util/date-util.spec.js
Labels: tech
