Repository LAB-MI/candilibV2, pull requests merged in 2020-11, with the labels that each got.

#1361 :lock: Npm audit fix
  client/package-lock.json
  client/package.json
  client/tests/e2e/specs/adminCandidatSearch.js
  client/tests/e2e/specs/adminUsers.js
  client/tests/e2e/specs/util/util-cypress.js
  client/tests/e2e/support/commands.js
  server/package-lock.json
Labels: dependencies

#1359 Tech/add joi validator
  client/src/views/candidat/Candidat.vue
  client/src/views/candidat/components/departement-selection/MessageInfoCenters75.vue
  client/tests/e2e/specs/admin-centres.js
  client/tests/e2e/specs/adminCandidatSearch.js
  client/tests/e2e/specs/adminPlanning.js
  client/tests/e2e/specs/util/util-cypress.js
  client/tests/e2e/support/commands.js
  server/db/app/app.js
  server/src/models/centre/centre-queries.js
  server/src/models/centre/centre-validator.js
  server/src/models/departement/departement-queries.js
  server/src/models/departement/departement-validator.js
  server/src/models/inspecteur/inspecteur-queries.js
  server/src/models/inspecteur/inspecteur-validator.js
  server/src/models/place/place-validator.js
  server/src/models/place/place.queries.js
  server/src/models/place/place.queries.spec.js
  server/src/models/user/user-validator.js
  server/src/models/user/user.queries.js
  server/src/models/user/user.queries.spec.js
  server/src/routes/admin/places-controllers.spec.js
  server/src/util/regex.js
Labels: server, tech

#1365 :pencil2: Update Faq
  client/src/views/candidat/components/faq/FaqJson.js
Labels: candidat, wording

#1214 Fix Cypress and db-rest Dockerfile config to build with internal registry
  client/e2e.Dockerfile
  client/src/views/CandidatHome.vue
  client/tests/e2e/specs/util/util-cypress.js
  server/db/app/Dockerfile
Labels: devops

#1366 :pencil1: Update email convocation
  server/src/routes/business/build-mail-convocation.js
  server/src/routes/business/mail/convocation-template.js
Labels: candidat, server, wording

#1371 :pencil2: fix typo
  client/src/views/candidat/components/faq/FaqJson.js
Labels: wording

#1375 Tech/upgrade node slim 14.15
  client/Dockerfile
  client/package-lock.json
  client/package.json
  client/src/components/AppEvaluation.stories.js
  client/src/components/BandeauBeta.stories.js
  client/src/components/ConfirmBox.stories.js
  client/src/components/Hexagon.stories.js
  client/src/stories/admin.stories.js
  client/src/stories/admin/import.places.stories.js
  client/src/stories/candidat.stories.js
  client/src/stories/common.stories.js
  client/src/stories/common/appsnackbar.stories.js
  client/src/views/admin/components/CandilibAutocomplete.stories.js
  client/src/views/admin/components/DepartementSelector.stories.js
  client/src/views/admin/components/EmailPasswordReset.stories.js
  client/src/views/admin/components/SearchCandidat.stories.js
  client/src/views/admin/components/SearchEmail.stories.js
  client/src/views/admin/components/SearchInspecteur.stories.js
  client/src/views/admin/components/WeekMonitor.stories.js
  client/src/views/admin/components/Whitelist.stories.js
  client/src/views/admin/components/schedule/GenerateInspecteurBordereaux.stories.js
  client/src/views/admin/components/schedule/ScheduleInspector.stories.js
  client/src/views/admin/components/schedule/ScheduleInspectorDetails.stories.js
  client/src/views/admin/components/searchInspecteur/ListSearchInspecteursAvailable.stories.js
  client/src/views/admin/components/statsKpi/StatsKpi.stories.js
  client/src/views/candidat/components/CandidatStepper.stories.js
  client/src/views/candidat/components/LandingPage.stories.js
  client/src/views/candidat/components/center-selection/CenterSelection.stories.js
  client/src/views/candidat/components/selection-summary/ReservationInfo.stories.js
  client/src/views/candidat/components/time-slots-selection/TimeSlot.stories.js
  client/src/views/candidat/components/time-slots-selection/TimeSlotsSelection.stories.js
  client/tests/e2e/specs/adminUsers.js
  server/Dockerfile
Labels: dependencies

#1378 delete duplicates codes in folder public
  server/src/routes/public/index.js
  server/src/routes/public/public-controllers.js
Labels: tech

#1368 fix unit test Login
  client/src/views/admin/components/Login.vue.spec.js
Labels: tech

#1380 refacto validator candidat
  client/src/views/admin/components/Login.vue.spec.js
  server/package-lock.json
  server/package.json
  server/src/models/candidat/candidat-validator.js
  server/src/models/candidat/candidat.queries.js
  server/src/util/validators/candidat-validator.js
  server/src/util/validators/candidat-validator.spec.js
  server/src/util/validators/validator.js
Labels: tech

#1387 :bug: fix warning tailwind modify bg-login jpg
  client/src/assets/bg-login.jpg
  client/src/assets/bg-login.ori.jpg
  client/tailwind.config.js
  client/vue.config.js
Labels: bug
