Repository LAB-MI/candilibV2, pull requests merged in 2020-04, with the labels that each got.

#1066 Feat/add departement geographic in centre API
  server/db/scripts/updateCentresWithGeoDep.js
  server/src/models/centre/centre-model.js
  server/src/models/centre/centre-queries.js
  server/src/models/centre/centre-queries.spec.js
  server/src/routes/common/centre-business.js
  server/src/routes/common/centre-business.spec.js
  server/src/routes/common/centre-controllers.js
  server/src/routes/common/centre-controllers.spec.js
Labels: EPIC: Changement de departement

#1081 :bug: fix in wording mail 24 heures to 40 heures
  server/src/routes/business/mail/epreuve-pratique-failed-template.js
  server/src/routes/business/mail/epreuve-pratique-ok-template.js
Labels: admin

#1062 Feat/change departement pre inscription #1043
  client/src/views/admin/components/SelectDepartements.vue
  client/src/views/candidat/components/SignupForm.vue
  client/tests/e2e/specs/candidateLogin.js
  client/tests/e2e/support/commands.js
  server/src/models/candidat/candidat.model.js
  server/src/models/candidat/candidat.queries.js
Labels: EPIC: Changement de departement

#1082 Feat/to change administrative departement when there are a booking
  server/src/models/__tests__/candidats.js
  server/src/models/candidat/candidat.queries.js
  server/src/routes/admin/places-business.js
  server/src/routes/admin/places-controllers.spec.js
  server/src/routes/candidat/middlewares/verify-candidat.js
  server/src/routes/candidat/middlewares/verify-candidat.spec.js
  server/src/routes/candidat/places-controllers.js
  server/src/routes/candidat/places-controllers.spec.js
Labels: EPIC: Changement de departement

#1063 :tada: Add departement selection page and logical
  client/src/api/api-paths.js
  client/src/api/index.js
  client/src/candidat.js
  client/src/constants.js
  client/src/router.js
  client/src/store/center.js
  client/src/store/departements.js
  client/src/views/CandidatHome.vue
  client/src/views/candidat/components/center-selection/CenterSelection.vue
  client/src/views/candidat/components/center-selection/CenterSelectionContent.vue
  client/src/views/candidat/components/departement-selection/DepartementSelection.vue
  client/src/views/candidat/components/departement-selection/DepartementSelectionContent.vue
  client/src/views/candidat/components/selection-summary/MyReservation.vue
  client/src/views/candidat/components/selection-summary/SelectionSummary.vue
  client/src/views/candidat/components/time-slots-selection/TimeSlot.vue
  client/src/views/candidat/components/time-slots-selection/TimesSlotsSelector.vue
  client/tests/e2e/specs/candidateFront.js
  server/src/models/__tests__/centres.js
  server/src/models/centre/centre-queries.js
  server/src/models/centre/centre-queries.spec.js
  server/src/routes/admin/message.constants.js
  server/src/routes/candidat/departement-controllers.spec.js
  server/src/routes/candidat/departements-business.js
  server/src/routes/candidat/departements-controllers.js
  server/src/routes/candidat/index.js
  server/src/routes/candidat/places-business.js
  server/src/routes/candidat/util/date-etg-candidat.js
  server/src/routes/candidat/util/index.js
  server/src/routes/common/centre-business.js
  server/src/routes/common/centre-controllers.js
Labels: EPIC: Changement de departement, candidat, server

#1020 Devops/use npm ci
  ci/init-db-e2e.sh
  client/Dockerfile
  server/Dockerfile
  server/package-lock.json
Labels: tech

#1105 Fix test e2e in candidat front
  client/cypress.env.json
  client/tests/e2e/specs/candidateFront.js
  client/tests/e2e/specs/candidateLogin.js
  client/tests/e2e/specs/delayAfterFailure.js
  client/tests/e2e/specs/interactions.js
Labels: client, tech

#1092 :arrow_up: upgrade vue-cli plugin
  client/package-lock.json
  client/package.json
Labels: tech

#1107 :arrow_up: Upgrade babel preset env and add es2020 feature
  server/babel.config.js
  server/package-lock.json
  server/package.json
Labels: tech
